simulate test failure

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,4 +10,5 @@ jobs:
             - name: Run fake tests
               run: |
                   echo "Running tests..."
-                  echo "All tests passed!"
+                  echo "Simulating a test failure!"
+                  exit 1
